use_frameworks!

platform :ios, '8.0'

target 'JWWebImageCache_Example' do
   pod 'JWWebImageCache', :path => '../'
   pod 'YYWebImage'
   pod 'SDWebImage'
  target 'JWWebImageCache_Tests' do
    inherit! :search_paths
  end
end
